config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get '/history', to: 'home#history'
  get '/log',     to: 'home#log'
  post '/log',     to: 'home#log_create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ActiveRecord::Base
  has_many :scores, dependent: :destroy
  has_many :users, :through => :scores

  accepts_nested_attributes_for :scores

  validates :played_at, presence: true
  validate :scores_limit_valid
  validate :scores_over_twenty_one_valid
  validate :scores_diference_two_points_valid

  after_create :set_rating

  def me(user_id)
    users.me(user_id).first
  end

  def opponent(user_id)
    users.not_me(user_id).first
  end

  def score_me(user_id)
    scores.me(user_id).first
  end

  def score_oponent(user_id)
    scores.not_me(user_id).first
  end

  def score(user_id)
    if won(user_id)
      "#{score_me(user_id).points}-#{score_oponent(user_id).points}"
    else
      "#{score_oponent(user_id).points}-#{score_me(user_id).points}"
    end
  end

  def won(user_id)
    (score_me(user_id).points > score_oponent(user_id).points)
  end

  def played_date
    played_at.strftime("%b %m")
  end

  private

    def set_rating
      #puts users
      one = users.first
      two = users.last
      print one.inspect
      print "\n"
      print two.inspect
      print "\n"

      if won(one.id)
        one.rating += 1
        two.rating -= ((two.rating > 0) ? 1 : 0 )
      else
        two.rating += 1
        one.rating -= ((one.rating > 0) ? 1 : 0 )
      end


      #if User.all.order(:rating).pluck(:rating).uniq.first == 0
      #  if won(one.id)
      #    one.rating += 1
      #  else
      #    two.rating += 1
      #  end
      #else
      #  if won(one.id)
      #    raking_w = User.all.order(:rating).pluck(:id).index(one.id)
      #    raking_l = User.all.order(:rating).pluck(:id).index(two.id)
      #    print "won one \n"
      #    print raking_w
      #    print " - "
      #    print raking_l
      #    print "\n"
      #    diff = (raking_l - raking_w)
      #    one.rating += ((diff < 0) ? diff : 1 )
      #    two.rating -= ((two.rating > 0) ? 1 : 0 )
      #  else
      #    raking_w = User.all.order(:rating).pluck(:id).index(two.id)
      #    raking_l = User.all.order(:rating).pluck(:id).index(one.id)
      #    print "won two \n"
      #    print raking_w
      #    print " - "
      #    print raking_l
      #    print "\n"
      #    diff = (raking_l - raking_w)
      #    two.rating += ((diff < 0) ? diff : 1 )
      #    one.rating -= ((one.rating > 0) ? 1 : 0 )
      #  end
      #end

      one.save
      two.save
      print "------ \n \n \n"
    end

    def scores_limit_valid
      unless scores.length == 2
        errors.add(:scores, "they must be only 2")
      end
    end

    def scores_over_twenty_one_valid
      unless scores.map { |s| s.points if s.points >= 21 }.compact.any?
        errors.add(:scores, "at least some must be greater than 21")
      end
    end

    def scores_diference_two_points_valid
      points = scores.map(&:points).sort.reverse
      unless (points.first - points.last) >= 2
        errors.add(:scores, "must be at least 2 points")
      end
    end
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :user
  belongs_to :match

  scope :me, ->(user_id) { where(user_id: user_id) }  
  scope :not_me, ->(user_id) { where.not(user_id: user_id) }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable
  has_many :scores
  has_many :matches, through: :scores
  
  scope :me, ->(user_id) { where(id: user_id) }  
  scope :not_me, ->(user_id) { where.not(id: user_id) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_opponents, only: [:log, :log_create]
  

  def index
    @users = User.all.order(:rating).reverse
  end

  def history
    @matches = current_user.matches
  end

  def log
    @match = Match.new
    @match.scores.build(user: current_user, points:0)
    @match.scores.build(points:0)
    
  end

  def log_create
    @match = current_user.matches.new(params_match)
    if @match.save
      flash[:notice] = "Log game successfully created"
      redirect_to history_path
    else
      render 'log'
    end
  end

  private
    def params_match
      params.require(:match).permit(:played_at, scores_attributes: [:user_id, :points] )
    end

    def set_match
      @match = Match.find(params[:id]) rescue nil
    end

    def set_opponents
      @opponents = User.not_me(current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Oponent</th>
        <th>Score</th>
        <th>Result</th>
      </tr>
    </thead>
    <tbody>
      <% @matches.map do |match| %>
      <tr>
        <td><%= match.played_date %></td>
        <td><%= match.opponent(current_user.id).email  %></td>
        <td><%= match.score(current_user.id)  %></td>
        <td><%= match.won(current_user.id) ? "W" : "L" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>


<!-- 
<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('history.png') %>
-->

app/views/home/index.html.erb
<h1 class='page-header'>Leaderboard</h1>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Raking</th>
        <th>Email</th>
        <th>Score</th>
        <th>Games played</th>
      </tr>
    </thead>
    <tbody>
      <% @users.map.with_index do |user, i| %>
      <tr>
        <td><%= i + 1 %></td>
        <td><%= user.email  %></td>
        <td><%= user.rating  %></td>
        <td><%= user.matches.length %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<!--
<div class="alert alert-warning" role="alert">This is a sample page.</div>

<%= image_tag('leaderboard.png') %>

-->

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>

<% if @match.errors.any? %>
  <div class="alert alert-icon alert-dismissible alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <i class="fa fa-times" aria-hidden="true"></i>
    </button>
    <strong>You have <%= pluralize(@match.errors.count, "error") %></strong> 
    <ul>
      <% @match.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %> 
<div class="col-md-12">
  <%= form_for(@match, url: log_path) do |f| %>
    <div class="field">
      <%= f.label :played_at %>
      <%= f.date_field :played_at, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.fields_for :scores do |s| %>
        <% if s.object.user == current_user %>
          <%= s.label :user_id, "User" %>
          <%= s.hidden_field :user_id, class: "form-control" %>  
          <%= s.label :user_id, "Your score" %>
          <%= s.text_field :points, class: "form-control" %>
        <% else %>
          <%= s.label :user_id, "Opponent" %>

          <%= s.collection_select(:user_id, @opponents, :id, :email, {}, class: "form-control") %>


          <%= s.label :user_id, "Their score" %>
          <%= s.text_field :points, class: "form-control" %>
        <% end %>
      <% end %>
    </div>
    <div class="actions">
      <%= f.submit "Save", class: "btn btn-lg btn-primary btn-create" %>
      <%= link_to "Cancel", root_path %>
    </div>
  <% end %>

<!--
<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('log_game.png') %>
-->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to 'Log Game', '/log', class: 'btn btn-success navbar-btn' %>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leadboard', root_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="/history">History</a></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>